image: node:latest


before_script:
  - npm config set proxy http://genproxy.amdocs.com:8080
  - npm config set https-proxy http://genproxy.amdocs.com:8080
  - export http_proxy=http://genproxy.amdocs.com:8080
  - export https_proxy=http://genproxy.amdocs.com:8080

cache:
  paths:
  - node_modules/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
  - npm install -g yarn
  - yarn install
  - yarn compile

test:
  stage: test
  script:
  - npm config get proxy
  - npm config get https-proxy
  - yarn install
  - yarn compile
  - yarn test


deploy:
  stage: deploy
  script:
  - yarn install
  - yarn compile
  - yarn dist:dir
  - yarn run pack
  - ftp -n < ./scripts/ftp_ci.txt
