image: node:latest


before_script:
  - npm config set proxy http://genproxy.amdocs.com:8080
  - npm config set https-proxy http://genproxy.amdocs.com:8080
  - export http_proxy=http://genproxy.amdocs.com:8080
  - export https_proxy=http://genproxy.amdocs.com:8080

cache:
  paths:
  - node_modules/

test:
  stage: test
  script:
  - npm config get proxy
  - npm config get https-proxy
  - npm install -g yarn
  - yarn install
  - yarn test
