image: node:latest


before_script:
  - npm config set proxy http://genproxy.amdocs.com:8080
  - npm config set https-proxy http://genproxy.amdocs.com:8080

cache:
  paths:
  - node_modules/

test:
  stage: test
  script:
  - npm install
  - npm lint
