# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

before_script:
  - wget http://nodejs.org/dist/node-latest.tar.gz 
  - tar -zxvf node-latest.tar.gz
  - mkdir ~/local
  - cd node-latest
  - ./configure --prefix=~/local
  - make install
  - npm install

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    
job1:
  script: "npm run release"